name: Gerar APK Android

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configurar Java (OpenJDK 17 para o Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar dependências do projeto
        run: npm install

      - name: Organizar arquivos web para o Capacitor
        run: |
          mkdir -p www
          cp index.html www/

      - name: Inicializar o ambiente Android do Capacitor
        run: npx cap add android

      - name: Inserir permissão de sobreposição (SYSTEM_ALERT_WINDOW) no Manifesto
        run: |
          sed -i '/<application/i \    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />' android/app/src/main/AndroidManifest.xml

      - name: Sincronizar arquivos com o projeto Android
        run: npx cap sync android

      - name: Compilar APK (Gradle Debug)
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Salvar o APK gerado
        uses: actions/upload-artifact@v4
        with:
          name: meu-aplicativo-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
